Add a new fuzzer that exercises code generation, optimization, and generated Python code (#150)
This commit makes many changes, mostly in support of a new fuzzing target.

This new fuzzing target, `drlojekyll-backend-fuzzer`, uses LibFuzzer along with its custom mutator capability to mutate syntactically valid Dr. Lojekyll programs using semantics-preserving mutations, executing the generated Python programs.  The big idea is that we will add self-testing Dr. Lojekyll programs to the `data/self_testing_examples` directory, which will be fuzz-tested briefly in CI after each commit.

Unlike the existing parser fuzzer, the new fuzzer performs mutations that should only result in syntactically-correct Dr. Lojekyll programs.

The fuzzer currently offers only one semantics-preserving mutation: one that randomly shuffles various components of the input Dr. Lojekyll program.  For example, clauses are permuted, and subclauses of each are also permuted.

Summary of fuzzing-related changes:
- Rename existing fuzzer binary from `fuzz` to `drlojekyll-parser-fuzzer`
- Add a new fuzzer to exercise everything after parsing (fixes #147)
- Run the new fuzzer for 1m in GitHub Actions CI after each commit
- Add a new directory `data/self_testing_examples`; .dr files added here will be picked up by CI fuzzing
- Make the transitive closure examples more thorough in their self-testing
- Add a vendored copy of the `reproc` subprocess library for C and C++
- Emit coarse statistics at the end-of-run of the existing parser fuzzer
- Fix a bug in the existing fuzzer crash minimization code
- Update parser fuzzing dictionary for `@highlight` pragma

Other changes:
- Run unit tests in parallel in CI, with random order
- Add a simple syntax file for Dr. Lojekyll for vim (fixes #52)
- Simplify existing parsing unit tests
- Change the default value of the CMake `ENABLE_TEST_MYPY_CHECKS` option to `ON`

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -15,7 +15,7 @@ env:
 #     - Build mode: debug or release
 #     - Fuzzing: enabled or disabled
 #     - macOS / several LTS versions of ubuntu / windows
-#     - gcc 8 / clang 6.0 / clang 9 / gcc 9
+#     - gcc 8 / clang 6.0 / clang 9 / gcc 9 / ...
 #     - ninja / makefiles / visual studio solution / xcode
 #
 # This would be hundreds of configurations, and it would be silly to test all
@@ -35,13 +35,14 @@ jobs:
           -DCMAKE_C_COMPILER=gcc-8
           -DCMAKE_CXX_COMPILER=g++-8
           -DWARNINGS_AS_ERRORS=1
+          -DENABLE_TEST_MYPY_CHECKS=OFF
           -DCMAKE_INSTALL_PREFIX="$DR_INSTALL_DIR"
           .
       - name: Build
         run: make -C build -j "$(nproc)"
 
       - name: Test
-        run: cd build && ctest --output-on-failure
+        run: cd build && ctest --output-on-failure -j 2 --schedule-random
 
       - name: Install
         run: |
@@ -70,13 +71,14 @@ jobs:
           -DCMAKE_C_COMPILER=clang-6.0
           -DCMAKE_CXX_COMPILER=clang++-6.0
           -DWARNINGS_AS_ERRORS=1
+          -DENABLE_TEST_MYPY_CHECKS=OFF
           -DCMAKE_INSTALL_PREFIX="$DR_INSTALL_DIR"
           .
       - name: Build
         run: cmake --build build -j "$(nproc)"
 
       - name: Test
-        run: cd build && ctest --output-on-failure
+        run: cd build && ctest --output-on-failure -j 2 --schedule-random
 
       - name: Install
         run: cmake --build build --target install
@@ -109,7 +111,6 @@ jobs:
           -DCMAKE_CXX_COMPILER=clang++-10
           -DENABLE_SANITIZERS=1
           -DENABLE_LIBFUZZER=1
-          -DENABLE_TEST_MYPY_CHECKS=ON
           -DWARNINGS_AS_ERRORS=1
           -DCMAKE_INSTALL_PREFIX="$DR_INSTALL_DIR"
           .
@@ -132,13 +133,14 @@ jobs:
             .
           cmake --build build
 
-      # Just a quick test to make sure the fuzzer doesn't crash immediately
-      - name: Test Debug Fuzzer
+      # Just a quick test to make sure the fuzzers don't crash immediately.
+      # More thorough fuzzing is done in a separate GitHub Actions workflow.
+      - name: Debug Parser Fuzzer Sanity Check
         run: |
-          mkdir -p fuzz-run/Debug
-          cp -r data/examples fuzz-run/Debug/corpus
-          cd fuzz-run/Debug
-          if ! ../../build/fuzz/Debug/fuzzer \
+          mkdir -p parser-fuzz-run/Debug
+          cp -r data/examples parser-fuzz-run/Debug/corpus
+          cd parser-fuzz-run/Debug
+          if ! ../../build/fuzz/Debug/drlojekyll-parser-fuzzer \
                  -max_total_time=3 \
                  -timeout=1 \
                  -max_len=400 \
@@ -146,7 +148,24 @@ jobs:
                  -dict=../../fuzz/dict.txt \
                  -exact_artifact_path=boom.txt \
                  corpus; then
-            echo >&2 "Fuzzing smoke test failed!"
+            echo >&2 "Parser fuzzer smoke test failed!"
+            echo >&2 "Base64-encoded input that triggered the failure:"
+            base64 >&2 boom.txt
+            exit 1
+          fi
+
+      - name: Debug Backend Fuzzer Sanity Check
+        run: |
+          mkdir -p backend-fuzz-run/Debug
+          cp -r data/self_testing_examples backend-fuzz-run/Debug/corpus
+          cd backend-fuzz-run/Debug
+          if ! ../../build/fuzz/Debug/drlojekyll-backend-fuzzer \
+                 -max_total_time=60 \
+                 -timeout=3 \
+                 -print_final_stats=1 \
+                 -exact_artifact_path=boom.txt \
+                 corpus; then
+            echo >&2 "Backend fuzzer smoke test failed!"
             echo >&2 "Base64-encoded input that triggered the failure:"
             base64 >&2 boom.txt
             exit 1
@@ -171,21 +190,45 @@ jobs:
           cmake --build build
 
       - name: Test Release
-        run: cd build && ctest -C RelWithDebInfo --output-on-failure
+        run: cd build && ctest -C RelWithDebInfo --output-on-failure -j 2 --schedule-random
 
-      # Just a quick test to make sure the fuzzer doesn't crash immediately
-      - name: Test Release Fuzzer
+      # Just a quick test to make sure the fuzzers don't crash immediately.
+      # More thorough fuzzing is done in a separate GitHub Actions workflow.
+      - name: Release Parser Fuzzer Sanity Check
         run: |
-          mkdir -p fuzz-run/RelWithDebInfo
-          cp -r data/examples fuzz-run/RelWithDebInfo/corpus
-          cd fuzz-run/RelWithDebInfo
-          ../../build/fuzz/RelWithDebInfo/fuzzer \
-            -max_total_time=3 \
-            -timeout=1 \
-            -max_len=400 \
-            -print_final_stats=1 \
-            -dict=../../fuzz/dict.txt \
-            corpus
+          mkdir -p parser-fuzz-run/RelWithDebInfo
+          cp -r data/examples parser-fuzz-run/RelWithDebInfo/corpus
+          cd parser-fuzz-run/RelWithDebInfo
+          if ! ../../build/fuzz/RelWithDebInfo/drlojekyll-parser-fuzzer \
+                 -max_total_time=3 \
+                 -timeout=1 \
+                 -max_len=400 \
+                 -print_final_stats=1 \
+                 -dict=../../fuzz/dict.txt \
+                 corpus; then
+            echo >&2 "Fuzzing smoke test failed!"
+            echo >&2 "Base64-encoded input that triggered the failure:"
+            base64 >&2 boom.txt
+            exit 1
+          fi
+
+      - name: Release Backend Fuzzer Sanity Check
+        run: |
+          mkdir -p backend-fuzz-run/RelWithDebInfo
+          cp -r data/self_testing_examples backend-fuzz-run/RelWithDebInfo/corpus
+          cd backend-fuzz-run/RelWithDebInfo
+          if ! ../../build/fuzz/RelWithDebInfo/drlojekyll-backend-fuzzer \
+                 -max_total_time=3 \
+                 -timeout=3 \
+                 -print_final_stats=1 \
+                 -exact_artifact_path=boom.txt \
+                 corpus; then
+            echo >&2 "Backend fuzzer smoke test failed!"
+            echo >&2 "Base64-encoded input that triggered the failure:"
+            base64 >&2 boom.txt
+            exit 1
+          fi
+
 
   build4:
     name: macOS 10.15 / Debug / Sanitizers
@@ -199,14 +242,13 @@ jobs:
           -G Xcode
           -DENABLE_SANITIZERS=1
           -DWARNINGS_AS_ERRORS=1
-          -DENABLE_TEST_MYPY_CHECKS=ON
           -DCMAKE_INSTALL_PREFIX="$DR_INSTALL_DIR"
           .
       - name: Build
         run: cmake --build build --config Debug -j "$(sysctl -n hw.ncpu)"
 
       - name: Test
-        run: cd build && ctest --output-on-failure
+        run: cd build && ctest --output-on-failure -j 2 --schedule-random
 
       - name: Install
         run: cmake --install build --config Debug
@@ -228,14 +270,13 @@ jobs:
           -B build
           -G "Visual Studio 16 2019"
           -DWARNINGS_AS_ERRORS=0
-          -DENABLE_TEST_MYPY_CHECKS=ON
           -DCMAKE_INSTALL_PREFIX="$env:DR_INSTALL_DIR"
           .
       - name: Build
         run: cmake --build build --config Debug -j
 
       - name: Test
-        run: cd build && ctest --output-on-failure
+        run: cd build && ctest --output-on-failure -j 2 --schedule-random
 
       - name: Install
         run: cmake --install build --config Debug
