Improve reproducibility of fuzzer smoke test
If the smoke test now evokes a crash within its brief execution time,
emit that output base64-encoded to stderr.  Someone could plausibly take
that and use it to reproduce the crash locally.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -137,13 +137,19 @@ jobs:
           mkdir -p fuzz-run/Debug
           cp -r data/examples fuzz-run/Debug/corpus
           cd fuzz-run/Debug
-          ../../build/fuzz/Debug/fuzzer \
-            -max_total_time=3 \
-            -timeout=1 \
-            -max_len=400 \
-            -print_final_stats=1 \
-            -dict=../../fuzz/dict.txt \
-            corpus
+          if ../../build/fuzz/Debug/fuzzer \
+               -max_total_time=3 \
+               -timeout=1 \
+               -max_len=400 \
+               -print_final_stats=1 \
+               -dict=../../fuzz/dict.txt \
+               -exact_artifact_path=boom.txt \
+               corpus; then
+            echo >&2 "Fuzzing smoke test failed!"
+            echo >&2 "Base64-encoded input that triggered the failure:"
+            base64 boom.txt >&2
+            exit 1
+          fi
 
       # Next, build RelWithDebInfo, using the indirect `cmake --build`
       # invocation of ninja.
